### ISSUE TITLE
Samples in the Android docs are ObjectiveC!

### ISSUE THREAD

**Issue by valdvir** [PayPal-Mobile/android-here-sdk-dist#30]
"Activating a card reader"

```objc
[[PayPalHereSDK sharedCardReaderManager] activateReader:readerOrNil];
```

We need Android sample code, or Android documentation. This happens in the PDF, in the online docs, and even in the README of this very repository.

There's no way to guess how the heck one should "active" a reader.

**Comment by lernerb** [comment]
Hi @valdvir, 

Ignoring the PDF -- Can you point us to the relevant code @ https://developer.paypal.com/docs/integration/paypal-here/android-dev/overview/ where you found this mistake?

We recently overhauled the developer documents and they should now be up to date with no objective c in the Android documents.

Thanks,
Brandon

**Comment by danielgindi** [comment]
This exists in the PDF under the "Activating a card reader" section, as @valdvir said.
It is very confusing. We have also not found any way to "activate" the reader and retrieve card data from it.

**Comment by lernerb** [comment]
The latest documentation for the CardReaderManager on android can be found [here] (http://paypal-mobile.github.io/android-here-sdk-dist/javadoc/com/paypal/merchant/sdk/CardReaderManager.html)

To get the card reader manager on android call `PayPalHereSDK.getCardReaderManager()` 

Are you trying to use the SDK's UI or are you trying to handle the events yourself?
Are you using a bluetooth/audio device -- if so which one?

Depending on the answers above I can help you with the proper code.

----

I see the code in objective c @ https://developer.paypal.com/docs/integration/paypal-here/android-dev/using-credit-card-data/. 'll relay this information to the owner as well.

**Comment by danielgindi** [comment]
We are trying to just access the reader, on the audio jack, and get the event of the "swipe" of the card, along with details that we can fill in the transaction.

**Comment by harishyarlagaddas** [comment]
@danielgindi @valdvir i Sorry for the confusion in documentation. We will correct the documentation soon.

To answer you question, You don't need to call activate reader api in Android SDK in order to get the swipe event. There are two ways to get the swipe event,

1. If you are using TransactionManager APIs to take payment then the sequence will be
    (a). call one of the beginPayment() api.
    (b). when the beginPayment() is called, TransactionManager will activate the connected card reader by calling waitForAuthorization() api of CardReaderManager.
   (c). If the application registers CardReaderListener, then the app will get onCardReadSuccess() callback on the registered CardReaderListener whenever swipe happens.
   (d). Now application can call appropriate flavor of processPayment() api of TransactionManager.

2. If the application wants to get the swipe data with out using TransactionManager then
  (a). Application should register CardReaderListener to CardReaderManager and call waitForAuthorization() api of CardReaderManger.
  (b). Now whenever swipe happens, application will be notified through onCardReadSuccess() callback of registered CardReaderListener.

Hope this helps to solve your issue. If not please let me know.
