### ISSUE TITLE
payment failure

### ISSUE THREAD

**Issue by hamidsani** [PayPal-Mobile/android-here-sdk-dist#37]
I've built a kiosk app that uses paypal here sdk and I've used the sample app as a reference. I have everything working and the work flow of my app is, an initial activity for sdk initalization, followed by the main activity with a paypal listener for successful card swipes. This works well. However, if the app is running for multiple hours then when I swipe the card it consistently results in payment failure. The only way around it is to re-initialize the app. I am assuming that this is a security feature of paypal to make sure that the token is refreshed every so often.

Now I have two questions, 1) is there anyways that I can detect when the access token needs to reinitialized? or what are the best practices for an app that needs to run continuously without any over-watch for weeks? 2) I know that according to the documentation when taking payment I can use something other than the custom SDK UI, but I can't find any specific example and I haven't had the best time deciphering the documentation. Does anyone have any examples or information that could share? Thanks

**Comment by ppmtscory** [comment]
The access token is valid for only 8 hours.  You can either do your own timing and generate a new access token prior to expiry or the SDK has functionality built in to notify you of an expired token.  This way you can be notified of an expired token prior to you receiving an authentication error from a service call.  You need to implement the [AuthenticationListerner](http://paypal-mobile.github.io/android-here-sdk-dist/javadoc/index.html) so that you can have your system generate a new access token when the `onInvalidToken()` method is called. 

As for the UI, it's highly recommended to utilize the UI that's currently within the SDK.  This is a requirement if you are processing with our EMV reader.  If you are just using the triangle dongles, you can utilize your own UI and simply use the methods of TransactionManager without the 'WithSDKUI'.  The full API documentation is found [here](http://paypal-mobile.github.io/android-here-sdk-dist/javadoc/index.html).

**Comment by hamidsani** [comment]
Great. Thank you very much. That makes sense and answered my questions

**Comment by hamidsani** [comment]
A quick questions. The easiest and fastest way of generating a new access token access today is to re-initialize the SDK, correct? Wondering if there are any other tricks to make it more transparent. My current setup is using two activities, one with paypal login and the other with the main activity and fragments. I can start the login activity once the token is expired by it often takes a few seconds to initialize the sdk and get setup. Wondering if there's an easier way.

**Comment by hamidsani** [comment]
Looks like I overlooked. The way to do is clearly explain on the paypal here [getting-started] (https://developer.paypal.com/docs/integration/paypal-here/android-dev/getting-started/) page. Just posting this in case someone else was interested.
