### ISSUE TITLE
Refresh token

### ISSUE THREAD

**Issue by hamidsani** [PayPal-Mobile/android-here-sdk-dist#42]
I noticed that the sample app demonstrate how to get an access token (last for 8 hours). I was wondering if the SDK is capable of retrieving a refresh token (never expires) instead and if so then any guidance would be high appreciated. The app I am making really needs me to login once every while necessary and I would like to set the token so it never expires and works. Thanks

**Comment by ppmtscory** [comment]
@hamidsani the access token is what's needed to utilize the SDK functionality - the refresh token wouldn't work.  The refresh of an access token can be handled in the SDK by implementing the [Authentication Listener](http://paypal-mobile.github.io/android-here-sdk-dist/javadoc/index.html).  When `onInvalidToken()` is called, you would have your app reach out to your cloud server to generate the new access token.  Otherwise, you could always set a timer to automatically refresh the access token every 7 hours.

**Comment by djMax** [comment]
Generally you shouldn't put the refresh token on the device - it's not safe. See this for a long discussion of why: https://github.com/paypal/paypal-retail-node . But, as Cory says, you just need to provide a server (can stick it on heroku for free) that will refresh the token on behalf of the device. The SDK will automatically take care of asking your server for it when it needs it.

**Comment by hamidsani** [comment]
Okay, great. I've give that a try. I tried to grab a new access token every 7 hours in the past but I ran into a few issues doing so and never got it to run properly. I guess I'll take another good look at it again. Is there any where with an example that implement this?
