### ISSUE TITLE
Paypal Here invoices

### ISSUE THREAD

**Issue by brooth** [PayPal-Mobile/android-here-sdk-dist#77]
Sorry if it's not right place for this issue but I really can't find more appropriate one.

I can't receive my paid invoices via https://api.sandbox.paypal.com/v1/invoicing/invoices, it always returns empty list. But I can receive an invoice details via https://api.sandbox.paypal.com/v1/invoicing/invoices/. Also, I found this link https://www.sandbox.paypal.com/webapps/hereapi/merchant/v1/invoices which works fine and returns a list of all my invoices. Nevertheless, I need a way to search through all my invoices, e.g. for a certain period. Rest service https://api.sandbox.paypal.com/v1/invoicing/search also doesn't work for me and alwayes returns empty list w/out any errors.

Any help?

**Comment by ppmtscory** [comment]
For PPH, you can use `https://api.sandbox.paypal.com/retail/merchant/v1/invoices` for the search and also `https://api.sandbox.paypal.com/retail/merchant/v1/invoices/<invoice ID>` for the invoice details.  If you are wanting to use the regular REST API endpoint for the search, then you need to add an additional HEADER to tell the system to look for PPH created invoices rather than REST API created invoices.  That header is `X-PAYPAL-REQUEST-SOURCE: MPA-DEVICE`.  I'd recommend just using the `/retail/merchant/v1/invoices` endpoint but ultimately it's up to you.
